name: amlproj06_training_env
dependencies:
  - python=3.8.*
  - pip=24.0

  - pip:
      - azureml-sdk
      - azureml-defaults
      - numpy
      - inference-schema[numpy-support]
      - azure-storage-blob
      - joblib
      - pandas
      - msal-extensions
      - cryptography
      - numpy
      - scikit-learn
      - openpyxl